openapi: '3.0.3'
info:
  title: Cards of Keyforge
  version: '0.1'
servers:
  - url: https://cardsofkeyforge.com/{basePath}
    variables:
      basePath:
        default: v1
paths:
  /cards/{id}:
    get:
      x-amazon-apigateway-integration:
        type: aws_proxy
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RetrieveCard.Arn}/invocations
        connectionType: INTERNET
        passthroughBehavior: NEVER
        httpMethod: POST
      summary: Returns a card by ID.
      tags:
        - cards
      parameters:
        - in: path
          name: id
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
components:
  schemas:
    Card:
      type: object

