name: build

on:
  push:
    branches:
      - master
      - main
    paths:
      - "lambda/**"
      - "test/**"
      - "internal/**"
      - "api/**"
      - "cloudformation.yml"
  pull_request:
    paths:
      - "lambda/**"
      - "test/**"
      - "internal/**"
      - "api/**"
      - "cloudformation.yml"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Install dependencies
        run: make install_deps

      - name: Build
        run: go build -v ./...

      - name: Test
        run: make test_all
