name: deploy

on:
  workflow_run:
    workflows: ["build"]
    branches: [main]
    types:
      - completed


jobs:

  deploy:
    if: ${{ github.ref == 'refs/heads/main' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Update cloudformation API spec
      uses: ItsKarma/aws-cli@v1.70.0
      with:
        args: s3 cp api/openapi.yaml s3://cards-keyforge/openapi/openapi-${{ github.sha }}.yaml

    - name: Build
      run: make build_all

    - name: Zip binaries
      run: make zip_functions

    - name: Upload functions to S3
      uses: ItsKarma/aws-cli@v1.70.0
      with:
        args: s3 cp build/ s3://cards-keyforge/functions/ --recursive --exclude "*" --include "*.zip"

    - name: Deploy to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: cardsofkeyforge-backend
        template: cloudformation.yml
        capabilities: "CAPABILITY_AUTO_EXPAND,CAPABILITY_IAM"
        parameter-overrides: GithubHash=${{ github.sha }}
